version: 2.0.{build}
image: Previous Visual Studio 2019
configuration:
- Debug
- Release
platform: Any CPU
clone_folder: C:\TheCrafters001\Build\TF2-Mod-Installer\src\bin
before_build:
- ps: nuget restore 'C:\TheCrafters001\Build\TF2-Mod-Installer\src\bin\src\versions\2.x\TF2 Mod Installer.sln'
build:
  project: src\versions\2.x\TF2 Mod Installer.sln
  verbosity: minimal
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: Da1vU7llzLm5JDUh7d+CmqZP3Bcy8WrelfYG5GxLRV1TRFLY1mKeoCN79E3kFUvA
  prerelease: true
  force_update: false