Public Class my_Custom_Stuff_Gen
    Public Shared Sub Generate()
        Console.WriteLine("Creating the my_custom_stuff folders")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\ambient")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\ambient_mp3")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\coach")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\commentary")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\doors")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\items")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\midi")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\misc")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\music")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\mvm")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\passtime")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\physics")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\pl_hoodoo")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\plats")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\player")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\replay")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\ui")
        MkDir(My.Settings.CustomFolder + "\my_custom_stuff\sound\weapons")
    End Sub
End Class
